--------------------------------
loading CUDA 12.8 with cuDNN / NCCL
based on cuda_12.8.0_570.86.10_linux.run
--------------------------------

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
Mon Aug 25 14:55:50 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.8     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-SXM2-32GB           On  | 00000000:1B:00.0 Off |                    0 |
| N/A   28C    P0              40W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2-32GB           On  | 00000000:1C:00.0 Off |                    0 |
| N/A   27C    P0              40W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2-32GB           On  | 00000000:3D:00.0 Off |                    0 |
| N/A   27C    P0              42W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2-32GB           On  | 00000000:3E:00.0 Off |                    0 |
| N/A   28C    P0              42W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2-32GB           On  | 00000000:B1:00.0 Off |                    0 |
| N/A   28C    P0              42W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2-32GB           On  | 00000000:B2:00.0 Off |                    0 |
| N/A   28C    P0              43W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2-32GB           On  | 00000000:DB:00.0 Off |                    0 |
| N/A   29C    P0              41W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2-32GB           On  | 00000000:DC:00.0 Off |                    0 |
| N/A   26C    P0              42W / 300W |      0MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
True 8
[2025-08-25 14:55:54,680] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:55:57,910] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-25 14:55:58,918] [WARNING] [runner.py:220:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected VISIBLE_DEVICES=0,1,2,3,4,5,6,7: setting --include=localhost:0,1,2,3,4,5,6,7
[2025-08-25 14:55:58,918] [INFO] [runner.py:610:main] cmd = /home/u8644434/miniconda3/envs/deepspeed/bin/python3.12 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None /work/u8644434/LLM/run/native.py --deepspeed_config /work/u8644434/LLM/configs/zero_3.json --batch_size 1 --seq_len 350 --total_steps 100
[2025-08-25 14:56:00,661] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:03,953] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-25 14:56:04,976] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2025-08-25 14:56:04,976] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=8, node_rank=0
[2025-08-25 14:56:04,976] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2025-08-25 14:56:04,976] [INFO] [launch.py:164:main] dist_world_size=8
[2025-08-25 14:56:04,976] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[2025-08-25 14:56:04,977] [INFO] [launch.py:256:main] process 316254 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=0', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:04,977] [INFO] [launch.py:256:main] process 316255 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=1', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:04,978] [INFO] [launch.py:256:main] process 316256 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=2', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:04,979] [INFO] [launch.py:256:main] process 316257 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=3', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:04,979] [INFO] [launch.py:256:main] process 316258 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=4', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:04,980] [INFO] [launch.py:256:main] process 316259 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=5', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:04,982] [INFO] [launch.py:256:main] process 316260 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=6', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:04,983] [INFO] [launch.py:256:main] process 316261 spawned with command: ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=7', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100']
[2025-08-25 14:56:07,243] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:07,294] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:07,311] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:07,417] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:07,505] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:07,544] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:08,291] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:08,347] [INFO] [real_accelerator.py:254:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-08-25 14:56:11,190] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-25 14:56:11,437] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-25 14:56:11,671] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-25 14:56:11,729] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-25 14:56:11,749] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[2025-08-25 14:56:11,882] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
Traceback (most recent call last):
  File "/work/u8644434/LLM/run/native.py", line 153, in <module>
    main()
  File "/work/u8644434/LLM/run/native.py", line 78, in main
    dist.init_process_group(
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1757, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 278, in _env_rendezvous_handler
    store = _create_c10d_store(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 198, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/work/u8644434/LLM/run/native.py", line 153, in <module>
    main()
  File "/work/u8644434/LLM/run/native.py", line 78, in main
    dist.init_process_group(
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1757, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 278, in _env_rendezvous_handler
    store = _create_c10d_store(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 198, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
Traceback (most recent call last):
  File "/work/u8644434/LLM/run/native.py", line 153, in <module>
    main()
  File "/work/u8644434/LLM/run/native.py", line 78, in main
    dist.init_process_group(
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1757, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 278, in _env_rendezvous_handler
    store = _create_c10d_store(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 198, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
[2025-08-25 14:56:15,839] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
Traceback (most recent call last):
  File "/work/u8644434/LLM/run/native.py", line 153, in <module>
    main()
  File "/work/u8644434/LLM/run/native.py", line 78, in main
    dist.init_process_group(
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1757, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 278, in _env_rendezvous_handler
    store = _create_c10d_store(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 198, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
[2025-08-25 14:56:15,881] [INFO] [logging.py:107:log_dist] [Rank -1] [TorchCheckpointEngine] Initialized with serialization = False
Traceback (most recent call last):
  File "/work/u8644434/LLM/run/native.py", line 153, in <module>
    main()
  File "/work/u8644434/LLM/run/native.py", line 78, in main
    dist.init_process_group(
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1757, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 278, in _env_rendezvous_handler
    store = _create_c10d_store(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 198, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package words to /home/u8644434/nltk_data...
[nltk_data]   Package words is already up-to-date!
[2025-08-25 14:56:19,990] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316254
[2025-08-25 14:56:20,007] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316255
[2025-08-25 14:56:20,019] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316256
Traceback (most recent call last):
  File "/work/u8644434/LLM/run/native.py", line 153, in <module>
    main()
  File "/work/u8644434/LLM/run/native.py", line 78, in main
    dist.init_process_group(
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1757, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 278, in _env_rendezvous_handler
    store = _create_c10d_store(
            ^^^^^^^^^^^^^^^^^^^
  File "/home/u8644434/miniconda3/envs/deepspeed/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 198, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
torch.distributed.DistNetworkError: The server socket has failed to listen on any local network address. port: 29500, useIpv6: false, code: -98, name: EADDRINUSE, message: address already in use
[2025-08-25 14:56:20,376] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316257
[2025-08-25 14:56:20,376] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316258
[2025-08-25 14:56:20,392] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316259
[2025-08-25 14:56:20,403] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316260
[2025-08-25 14:56:20,466] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 316261
[2025-08-25 14:56:20,535] [ERROR] [launch.py:325:sigkill_handler] ['/home/u8644434/miniconda3/envs/deepspeed/bin/python3.12', '-u', '/work/u8644434/LLM/run/native.py', '--local_rank=7', '--deepspeed_config', '/work/u8644434/LLM/configs/zero_3.json', '--batch_size', '1', '--seq_len', '350', '--total_steps', '100'] exits with return code = 1
